name = "monzo-balancer"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "monzo-balancer"
database_id = "6abc45d1-f74c-4968-8450-e1b784d5c231"

[observability.logs]
enabled = true

[vars]
MONZO_CLIENT_ID = "oauth2client_0000B253u1ZmFYn2GzFWLK"
MONZO_REDIRECT_URI = "https://monzo-balancer.dh.workers.dev/oauth/callback"
